### ISSUE TITLE
[dropwizard-jobs-guice] Injector does not contain Job classes

### ISSUE THREAD

**Issue by danielfc** [dropwizard-jobs/dropwizard-jobs#53] opened 2017-03-22 15:02 UTC
https://github.com/spinscale/dropwizard-jobs/blob/master/dropwizard-jobs-guice/src/main/java/de/spinscale/dropwizard/jobs/GuiceJobManager.java#L24

It turns out that `injector.getBindings()` doesn't contain my `Job` classes, therefore, the jobs don't get instantiated. Am I missing something? I'm using 3.0.0 versions of `dropwizard-jobs` and `dropwizard-jobs-guice`, 1.0.6 version of `dropwizard` and 1.0.6.0 of `dropwizard-guice`.

```java
  private final GuiceBundle<OperationsConfiguration> guiceBundle =
      GuiceBundle.<OperationsConfiguration>newBuilder()
          .addModules(new Module())
          .enableAutoConfig(getClass().getPackage().getName())
          .setConfigClass(OperationsConfiguration.class)
          .build();
```

```java
// initialize()
bootstrap.addBundle(guiceBundle);
bootstrap.addBundle(new GuiceJobsBundle(guiceBundle.getInjector()));
```

```java
// job
@Every("60s")
public class ExampleJob extends Job {
 
  private final ExampleService exampleService;

  @Inject
  public ExampleJob(ExampleService exampleService) {
    this.exampleService = exampleService;
  }
 
  @Override
  public void doJob(JobExecutionContext context) throws JobExecutionException {
 ...
```

I appreciate any help.

**Comment by alangiles** [comment] 2017-04-17 11:14
I ran into the same issue. I discovered the following. You need to have a bind for your ExampleJob class in Module like below.

```java
public class Module extends AbstractModule {
	@Override
	protected void configure() {
		bind(ExampleJob.class);
	}
}
```

Then in your Application initialise() if you perform the following it works.
```java
bootstrap.addBundle(new GuiceJobsBundle(guiceBundle.getInjector().getParent()));
```

The reason is that your module bindings is added to baseInjector in [GuiceBundle.initialise()](https://github.com/HubSpot/dropwizard-guice/blob/dropwizard-guice-1.0.6.0/src/main/java/com/hubspot/dropwizard/guice/GuiceBundle.java#L133) however when you call guiceBundle.getInjector() this [GuiceBundle.getInjector()](https://github.com/HubSpot/dropwizard-guice/blob/dropwizard-guice-1.0.6.0/src/main/java/com/hubspot/dropwizard/guice/GuiceBundle.java#L164) returns a child injector of baseInjector that doesnt contain the correct bindings.

A potential PR is to change [GuiceJobManager.getJobs()](https://github.com/spinscale/dropwizard-jobs/blob/master/dropwizard-jobs-guice/src/main/java/de/spinscale/dropwizard/jobs/GuiceJobManager.java#L24) to get the parents injector `injector.getParent().getBindings()` bindings by changing from 

```java
    static Job[] getJobs(Injector injector) {
        List<Job> jobs = new ArrayList<>();
        for (Map.Entry<Key<?>, Binding<?>> entry : injector.getBindings().entrySet()) {
            Class<?> clazz = entry.getValue().getKey().getTypeLiteral().getRawType();
            if (Job.class.isAssignableFrom(clazz)) {
                jobs.add((Job) injector.getInstance(clazz));
            }
        }
        return jobs.toArray(new Job[]{});
    }
```
to
```java
    static Job[] getJobs(Injector injector) {
        List<Job> jobs = new ArrayList<>();
        for (Map.Entry<Key<?>, Binding<?>> entry : injector.getParent().getBindings().entrySet()) {
            Class<?> clazz = entry.getValue().getKey().getTypeLiteral().getRawType();
            if (Job.class.isAssignableFrom(clazz)) {
                jobs.add((Job) injector.getInstance(clazz));
            }
        }
        return jobs.toArray(new Job[]{});
    }
```

Hope this helps.

Happy to work on a PR if this is the correct approach.

**Comment by danielforberg** [comment] 2017-08-01 17:30
Your bugfix did not work. /Daniel

**Comment by alangiles** [comment] 2017-08-03 11:08
I've created a repo [dropwizard-jobs-issue-53](https://github.com/alangiles/dropwizard-jobs-issue-53) that showcases the fix working. I'm using version 3.0.0 of `dropwizard-jobs` and `dropwizard-jobs-guice`, 1.0.6 version of `dropwizard` and 1.0.6.0 of `dropwizard-guice`.

**Comment by danielforberg** [comment] 2017-08-03 11:44
Ok same versions here. And dropwizard 1.1.0. But get massive error message. Something about the order before bootstrap .... Did'nt use guice autoconfig. Cause i could'nt for old crappy code did not work. To have autoconfig. Currently i implemented a guava scheduler job solution.

**Comment by alangiles** [comment] 2017-08-03 13:25
Ive created a [branch 1.1.0](https://github.com/alangiles/dropwizard-jobs-issue-53/tree/1.1.0) and just tested with `enableAutoConfig` removed and `dropwizard` version 1.1.0 and it works.

**Comment by hakandilek** [comment] 2023-05-29 20:30
I'm closing this as this relates to an older version and the mentioned fix is confirmed.

**Closed by hakandilek** 2023-05-29 20:30 UTC
